name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Admin Manager Project
      run: |
        cd admin_manager
        npm ci
        npm run build
    
    - name: Build Website Project
      run: |
        cd website
        npm ci
        npm run build

